<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to numpy:
</p><br>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

<b>Additional Recommended Resources:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentation</a><br>
<i>Python for Data Analysis</i> by Wes McKinney<br>
<i>Python Data science Handbook</i> by Jake VanderPlas



<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Getting started with ndarray<br><br></p>

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy.  Like the data structures in Week 2, let's get started by creating ndarrays using the numpy package.

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

How to create Rank 1 numpy arrays:
</p>

In [1]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [2]:
# test the shape of the array we just created, it should have just one dimension (Rank 1)
print(an_array.shape)

(3,)


In [3]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


In [4]:
an_array[0] =888            # ndarrays are mutable, here we change an element of the array

print(an_array)

[888  33 333]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

How to create a Rank 2 numpy array:</p>

A rank 2 **ndarray** is one with two dimensions.  Notice the format below of [ [row] , [row] ].  2 dimensional arrays are great for representing matrices which are often useful in data science.

In [ ]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array

print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns                   

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

There are many way to create numpy arrays:
</p>

Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [2]:
import numpy as np

# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)                              

[[ 0.  0.]
 [ 0.  0.]]


In [ ]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

In [5]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)  

[[ 1.  0.]
 [ 0.  1.]]


In [6]:
# create an array of ones
ex4 = np.ones((1,2))
print(ex4)    

[[ 1.  1.]]


In [7]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [8]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)    

[[ 0.13071001  0.20945905]
 [ 0.08564571  0.26605972]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Array Indexing
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Slice indexing:
</p>

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

In [9]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [13]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


When you modify a slice, you actually modify the underlying array.

In [14]:
print("Before:", an_array[0, 1])   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])    

Before: 12
After: 1000


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Use both integer indexing & slice indexing
</p>

We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [18]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [19]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]    # Rank 1 view 

print(row_rank1, row_rank1.shape)  # notice only a single []

[21 22 23 24] (4,)


In [17]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [ ]:
#We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

Sometimes it's useful to use an array of indexes to access or change elements.

In [20]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [21]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [ ]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

In [ ]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

In [ ]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Boolean Indexing

<br><br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

In [27]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [23]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [24]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

[21 22 31 32]


In [25]:
# For short, we could have just used the approach below without the need for the separate filter array.

an_array[(an_array % 2 == 0)]

array([12, 22, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter.  Let's add 100 to all the even values.

In [26]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Datatypes and Array Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Datatypes:
</p>

In [28]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

int64


In [29]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [ ]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

In [30]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [31]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[ 11.  21.]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Arithmetic Array Operations:

</p>

In [32]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[ 211.1  212.1]
 [ 221.1  222.1]]


In [33]:
# add
print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"

[[ 322.1  324.1]
 [ 342.1  344.1]]

[[ 322.1  324.1]
 [ 342.1  344.1]]


In [34]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [35]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]


In [36]:
# divide
print(x / y)
print()
print(np.divide(x, y))

[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]

[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]


In [37]:
# square root
print(np.sqrt(x))

[[ 10.53565375  10.58300524]
 [ 11.          11.04536102]]


In [38]:
# exponent (e ** x)
print(np.exp(x))

[[  1.60948707e+48   4.37503945e+48]
 [  3.54513118e+52   9.63666567e+52]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Statistical Methods, Sorting, and <br> <br> Set Operations:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Basic Statistical Operations:
</p>

In [50]:
# setup a random 2 x 4 matrix
arr = np.random.randn(20,5)
print(arr)
print(arr.mean())

[[-0.91548724  1.16759741 -0.70162584  0.00696626 -2.20538128]
 [-0.29043339  1.57143543  1.99837398  0.78676079 -0.84970419]
 [ 0.51973056  0.29862239  1.34892982  1.43989301  0.09851801]
 [ 0.22357088  1.02923613  0.26246473 -0.27391595  0.1057603 ]
 [-1.76694911 -0.05101113 -0.06762457  0.21219836 -0.80174292]
 [ 1.70786078 -1.67451298  2.4247573   1.58109813  0.73934837]
 [ 0.77022835 -1.30874647  0.13776167 -0.34816131  0.0039073 ]
 [-1.59753907  0.59976977  0.23909036 -0.10951716  0.54404711]
 [ 0.02482686  0.6448255   0.16923688  1.55986994  1.77816524]
 [ 0.08686816 -0.67068159  2.05233665 -1.01241213  2.80643356]
 [ 1.02705239 -0.20453231  0.16644364  0.04443719 -0.36269741]
 [-0.33839797 -0.12409981 -1.48477147 -0.2368166  -1.23803187]
 [-0.57452762  1.88019537 -0.97975015 -0.2625317  -0.59628417]
 [ 0.64217185 -0.99251599 -0.81913939 -1.25283042  1.37935848]
 [ 0.23998606 -1.07728035 -1.36998803  0.4437049  -0.52433547]
 [-0.68157655  0.76795976 -1.14563337 -0.46481995  0.14

In [51]:
# compute the mean for all elements
print(arr.mean())

0.0667226112415


In [52]:
# compute the means by row
print(arr.mean(axis = 1))

[-0.52958614  0.64328652  0.74113876  0.26942322 -0.49502587  0.95571032
 -0.14900209 -0.0648298   0.83538488  0.65250893  0.1341407  -0.68442354
 -0.10657965 -0.20859109 -0.45758258 -0.27487697  0.17479996 -0.2715046
  0.02203396  0.14802731]


In [53]:
# compute the means by column
print(arr.mean(axis = 0))

[ -3.98689537e-02  -3.70650360e-02   1.44826022e-01   2.65462894e-01
   2.58129930e-04]


In [54]:
# sum all the elements
print(arr.sum())

6.67226112415


In [55]:
# compute the medians
print(np.median(arr, axis = 1))

[-0.70162584  0.78676079  0.51973056  0.22357088 -0.06762457  1.58109813
  0.0039073   0.23909036  0.6448255   0.08686816  0.04443719 -0.33839797
 -0.57452762 -0.81913939 -0.52433547 -0.46481995 -0.26702718 -0.46238842
  0.09719835 -0.25900762]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sorting:
</p>


In [ ]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

In [ ]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

In [ ]:
# inplace sorting
unsorted.sort() 

print(unsorted)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Finding Unique elements:
</p>

In [ ]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Set Operations with np.array data type:
</p>

In [56]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [57]:
print( np.intersect1d(s1, s2) ) 

['bulb' 'chair']


In [58]:
print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [59]:
print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2

['desk']


In [60]:
print( np.in1d(s1, s2) )#which element of s1 is also in s2

[False  True  True]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Broadcasting:
<br><br>
</p>

Introduction to broadcasting. <br>
For more details, please see: <br>
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [ ]:
import numpy as np

start = np.zeros((4,3))
print(start)

In [ ]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

In [ ]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

In [ ]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

Example from the slides:

In [ ]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

In [ ]:
# create our 4x1 array
arrB = [0,1,0,2]
print(arrB)

In [ ]:
# add the two together using broadcasting
print(arrA + arrB)

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Speedtest: ndarrays vs lists
<br><br>
</p>

First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [61]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [62]:
# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [63]:
# timer expects the operation as a parameter, 
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000454 seconds


In [64]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

<class 'list'>


In [65]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.005005 seconds


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Read or Write to Disk:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Binary Format:</p>

In [ ]:
x = np.array([ 23.23, 24.24] )

In [ ]:
np.save('an_array', x)

In [ ]:
np.load('an_array.npy')

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Text Format:</p>

In [ ]:
np.savetxt('array.txt', X=x, delimiter=',')

In [ ]:
!cat array.txt

In [ ]:
np.loadtxt('array.txt', delimiter=',')

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Additional Common ndarray Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Dot Product on Matrices and Inner Product on Vectors:

</p>

In [ ]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

In [ ]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

In [ ]:
# dot produce on an array and vector
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sum:
</p>

In [ ]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members

In [ ]:
print(np.sum(ex1, axis=0))  # columnwise sum

In [ ]:
print(np.sum(ex1, axis=1))  # rowwise sum

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Element-wise Functions: </p>

For example, let's compare two arrays values to get the maximum of each.

In [ ]:
# random array
x = np.random.randn(8)
x

In [ ]:
# another random array
y = np.random.randn(8)
y

In [ ]:
# returns element wise maximum between two arrays

np.maximum(x, y)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Reshaping array:
</p>

In [ ]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

In [ ]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Transpose:

</p>

In [ ]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Indexing using where():</p>

In [ ]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [ ]:
out = np.where(filter, x_1, y_1)
print(out)

In [ ]:
mat = np.random.rand(5,5)
mat

In [ ]:
np.where( mat > 0.5, 1000, -1)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

"any" or "all" conditionals:</p>

In [ ]:
arr_bools = np.array([ True, False, True, True, False ])

In [ ]:
arr_bools.any()

In [ ]:
arr_bools.all()

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Random Number Generation:
</p>

In [ ]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

In [ ]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

In [ ]:
np.random.permutation(Z) #return a new ordering of elements in Z

In [ ]:
np.random.uniform(size=4) #uniform distribution

In [ ]:
np.random.normal(size=4) #normal distribution

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Merging data sets:
</p>

In [ ]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

In [ ]:
np.vstack((K,M))

In [ ]:
np.hstack((K,M))

In [ ]:
np.concatenate([K, M], axis = 0)

In [ ]:
np.concatenate([K, M.T], axis = 1)

In [74]:
b = np.array([[11,12,13],[21,22,23]])
print(b)

[[11 12 13]
 [21 22 23]]


In [76]:
print(b[1,2])

23


In [77]:
arr = np.array([1,2,3,4,5])
arr[4]=7
print(arr)

[1 2 3 4 7]


In [78]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [79]:
print(arr[0:1,1:3])

[[2 3]]


In [80]:
print(arr[1,1:3])

[6 7]


In [81]:
print(arr[:1,1:3])

[[2 3]]


In [83]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
print(arr[:2,])

[[1 2 3]
 [4 5 6]]


In [85]:
print(arr)
slice = arr[:2,1:3]
print(slice[0,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [86]:
print(arr[0,1])

2


In [87]:
slice[0,0]=20
print(arr)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [88]:
print (arr>10)

[[False  True False]
 [False False False]
 [False False False]]


In [89]:
print(arr<0)

[[False False False]
 [False False False]
 [False False False]]


In [91]:
print(arr[arr<20])

[1 3 4 5 6 7 8 9]


In [92]:
print[arr[,]<0]

SyntaxError: invalid syntax (<ipython-input-92-0ee92f568f9b>, line 1)

In [93]:
slice[0,0]=2
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [94]:
print(arr[(arr % 2 != 0)])

[1 3 5 7 9]


In [95]:
print(arr[(arr % 2 == 1)])

[1 3 5 7 9]


In [96]:
a=np.array(["cat","dog","fish"])
b=np.array(["dog","fish","rabbit"])
print(np.setdiff1d(a,b))

['cat']


In [97]:
print(np.setdiff1d(b,a))

['rabbit']


In [98]:
A = np.array([[1],[2]])
B = np.array([[1,2],[3,4]])
A + B

array([[2, 3],
       [5, 6]])

In [99]:
a = np.array([2, 3])
b1 = np.array([1])
b2 = 1 
print(a+b1)
print(a+b2)

[3 4]
[3 4]
